### ISSUE TITLE
Customise environment variables per-runner

### ISSUE THREAD

**Issue by danmilleruk** [Telefonica/puppet-github-actions-runner#39]
Currently there is no option to configure environment variables on a per-runner basis. There are few instances where this is needed, but this is still greater than zero.

It would be great if we could pass environment variables to be written to .env on each runner.

This will also eventually be useful to customise the (currently in BETA) "ACTIONS_RUNNER_HOOK_JOB_STARTED" and "ACTIONS_RUNNER_HOOK_JOB_COMPLETED" environment variables, for running cleanup scripts, etc.

**Comment by mrodm** [comment]
Hi! Thanks for reporthing this issue.

This feature looks quite useful so runners can be further customized at host level if necessary. We'll take a look to it.

I guess it could be implemented using a similar logic to PR #37, and I've started this (draft) PR to work on this issue: #40 

As a reference, here I found the documentation about those environment variables and how they should be added into `.env` file:
- https://docs.github.com/en/actions/hosting-your-own-runners/running-scripts-before-or-after-a-job#triggering-the-scripts
