### ISSUE TITLE
Error: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/Archive[example_org_instance-actions-runner-linux-x64-2.285.1.tar.gz]/creates: change from 'archive not extracted' to extracting in /opt/actions-runner-2.285.1/example_org_instance to create /opt/actions-runner-2.285.1/example_org_instance/bin failed: Execution of 'tar xzf 

### ISSUE THREAD

**Issue by birb57** [Telefonica/puppet-github-actions-runner#44]
Hello 

First of all Good job

Can you please give me a sample common.yaml file for a specific github repo example

I am not sure what I need to set in the hiera file to have all my parameters set

[root@clientsat01 github_actions_runner]# puppet apply /etc/puppet/modules/github_actions_runner/tests/init.pp -vv
Info: Loading facts
Info: Loading facts
Info: Loading facts
Notice: Compiled catalog for clientsat01.cedelgroup.com in environment production in 0.21 seconds
Info: Applying configuration version '1654431815'
Notice: /Stage[main]/Github_actions_runner/File[/opt/actions-runner-2.285.1]/ensure: created
Notice: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/File[/opt/actions-runner-2.285.1/example_org_instance]/ensure: created
Error: Execution of 'tar xzf /tmp/example_org_instance-actions-runner-linux-x64-2.285.1.tar.gz' returned 2: gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/Archive[example_org_instance-actions-runner-linux-x64-2.285.1.tar.gz]/creates: change from 'archive not extracted' to extracting in /opt/actions-runner-2.285.1/example_org_instance to create /opt/actions-runner-2.285.1/example_org_instance/bin failed: Execution of 'tar xzf /tmp/example_org_instance-actions-runner-linux-x64-2.285.1.tar.gz' returned 2: gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Notice: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/File[/opt/actions-runner-2.285.1/example_org_instance/configure_install_runner.sh]: Dependency Archive[example_org_instance-actions-runner-linux-x64-2.285.1.tar.gz] has failures: true
Warning: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/File[/opt/actions-runner-2.285.1/example_org_instance/configure_install_runner.sh]: Skipping because of failed dependencies
Notice: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/Exec[example_org_instance-check-runner-configured]/returns: executed successfully
Info: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/Exec[example_org_instance-check-runner-configured]: Scheduling refresh of Exec[example_org_instance-run_configure_install_runner.sh]
Warning: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/Exec[example_org_instance-ownership]: Skipping because of failed dependencies
Warning: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/Exec[example_org_instance-run_configure_install_runner.sh]: Skipping because of failed dependencies
Info: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/Exec[example_org_instance-run_configure_install_runner.sh]: Unscheduling all events on Exec[example_org_instance-run_configure_install_runner.sh]
Warning: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/File[/opt/actions-runner-2.285.1/example_org_instance/.path]: Skipping because of failed dependencies
Warning: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_org_instance]/File[/opt/actions-runner-2.285.1/example_org_instance/.env]: Skipping because of failed dependencies
Notice: /Stage[main]/Github_actions_runner/Github_actions_runner::Instance[example_repo_instance]/File[/opt/actions-runner-2.285.1/example_repo_instance]/ensure: created
Error: Execution of 'tar xzf /t

Best regards
Many thanks for your help/support

**Comment by oscarsj** [comment]
Hi! Thanks for your words, and for using the module, we really appreciate feedback!

The bare minimum config would be something like what is shown in https://github.com/Telefonica/puppet-github-actions-runner#creating-an-organization-level-actions-runner

```puppet

# GitHub actions runner settings.
github_actions_runner::base_dir_name: '/srv/actions-runner'
github_actions_runner::org_name: 'MyOrganization'
github_actions_runner::personal_access_token: "%{hiera('github_repository_readonly_password')}"
```

From the stacktraces you posted, seems that there is some error downloading or extracting the runner package (https://github.com/actions/runner/releases/download/v2.285.1/actions-runner-linux-x64-2.285.1.tar.gz) from github, maybe disk space in the runner,  or downloading errors? it does not really seem a configuration problem , but if you post your current config maybe we can give it a look
